export interface Permission {
  key: string;
  label: string;
  category: "vendas" | "compras" | "financeiro" | "produtos" | "contratos" | "locacao" | "config" | "outros";
}

export const PERMISSIONS_MAP: Record<string, { label: string; category: Permission["category"] }> = {
  Op1: { label: "Venda de Produtos", category: "vendas" },
  Op2: { label: "Compra de Produtos", category: "compras" },
  Op3: { label: "Clientes", category: "outros" },
  Op4: { label: "Fornecedores", category: "outros" },
  Op5: { label: "Produtos", category: "produtos" },
  Op6: { label: "Produto", category: "produtos" },
  Op7: { label: "Grupo", category: "produtos" },
  Op8: { label: "Senha (Controle de Usuários)", category: "config" },
  Op9: { label: "Vendas", category: "vendas" },
  Op10: { label: "Compras", category: "compras" },
  Op11: { label: "Tabela de Preços", category: "financeiro" },
  Op12: { label: "Inventário", category: "produtos" },
  Op13: { label: "Supervisor", category: "config" },
  Op14: { label: "Baixa de Estoque e Transferência", category: "produtos" },
  Op15: { label: "Contas a Receber (Vencimento)", category: "financeiro" },
  Op16: { label: "Contas a Receber", category: "financeiro" },
  Op17: { label: "Contas a Pagar", category: "financeiro" },
  Op18: { label: "Forma de Caixa", category: "financeiro" },
  Op19: { label: "Forma de Pagamento", category: "financeiro" },
  Op20: { label: "Tipo Contábil", category: "financeiro" },
  Op21: { label: "Cadastro de Obras", category: "outros" },
  Op22: { label: "Cadastro de Acessórios", category: "produtos" },
  Op23: { label: "Cadastro de Equipamentos", category: "produtos" },
  Op24: { label: "Contrato", category: "contratos" },
  Op25: { label: "Histórico de Contatos / Ouvidoria 1", category: "outros" },
  Op26: { label: "Faturamento", category: "financeiro" },
  Op27: { label: "Produtos Pendentes", category: "produtos" },
  Op28: { label: "Configurações do Sistema", category: "config" },
  Op29: { label: "Segmento", category: "outros" },
  Op30: { label: "Contato", category: "outros" },
  Op31: { label: "Cancela Cupom Fiscal", category: "vendas" },
  Op32: { label: "Histórico de Contatos / Ouvidoria 2", category: "outros" },
  Op33: { label: "Relatório de NF Entrada e Saída", category: "financeiro" },
  Op34: { label: "Cadastro de Indicador", category: "config" },
  Op35: { label: "Comissões", category: "financeiro" },
  Op36: { label: "Filtro de Controle de Vendas", category: "vendas" },
  Op37: { label: "Mala Direta", category: "outros" },
  Op38: { label: "Entregas Pendentes", category: "vendas" },
  Op39: { label: "Compromissos de Usuário", category: "outros" },
  Op40: { label: "Reajuste de Preços", category: "financeiro" },
  Op41: { label: "Atualização de Estoque", category: "produtos" },
  Op42: { label: "Contas Bancárias", category: "financeiro" },
  Op43: { label: "Alterar Preço", category: "financeiro" },
  Op44: { label: "Frente de Loja - Processos", category: "vendas" },
  Op45: { label: "Consignação de Produtos", category: "produtos" },
  Op46: { label: "Venda de Produtos em Duplicidade", category: "vendas" },
  Op47: { label: "Tabela de Frete", category: "financeiro" },
  Op48: { label: "Tabela de Histórico", category: "outros" },
  Op49: { label: "Material para Serviço", category: "produtos" },
  Op50: { label: "Material para Locação", category: "locacao" },
  Op51: { label: "Acessório para Locação", category: "locacao" },
  Op52: { label: "Ordem de Serviço", category: "vendas" },
  Op53: { label: "O.S. / Vendas Realizadas", category: "vendas" },
  Op54: { label: "Locação de Materiais", category: "locacao" },
  Op55: { label: "Cálculo de Faturamento", category: "financeiro" },
  Op56: { label: "Equipamentos Locados", category: "locacao" },
  Op57: { label: "Histórico de Equipamento", category: "locacao" },
  Op58: { label: "CFOP", category: "financeiro" },
  Op59: { label: "Produção de Produtos", category: "produtos" },
  Op60: { label: "Grupo de Segmento", category: "outros" },
  Op61: { label: "Referência Bancária", category: "financeiro" },
  Op62: { label: "Conta Inadimplente", category: "financeiro" },
  Op63: { label: "Conhecimento", category: "outros" },
  Op64: { label: "Natureza", category: "financeiro" },
  Op65: { label: "Conhecimentos - Relatórios", category: "outros" },
  Op66: { label: "Contrato Secundário", category: "contratos" },
  Op67: { label: "Serviços", category: "outros" },
  Op68: { label: "Sepultado", category: "outros" },
  Op69: { label: "Gera Financeiro", category: "financeiro" },
  Op70: { label: "Interoperabilidade", category: "config" },
  Op71: { label: "Usuário Alterar Estoque", category: "produtos" },
  Op72: { label: "Transação", category: "financeiro" },
  Op73: { label: "Categoria", category: "produtos" },
  Op74: { label: "Centro de Resultado", category: "financeiro" },
  Op75: { label: "Empresa", category: "config" },
  Op76: { label: "Cadastro de Cor", category: "produtos" },
  Op77: { label: "Cadastro Vales", category: "financeiro" },
  Op78: { label: "Alterar Indicador 1", category: "config" },
  Op79: { label: "Finalizar Pedido", category: "vendas" },
  Op80: { label: "Devolução de Proposta", category: "vendas" },
  Op81: { label: "Simples Remessa", category: "vendas" },
  Op82: { label: "Controle de Cargas", category: "produtos" },
  Op83: { label: "Tabela de Setores", category: "config" },
  Op84: { label: "Tabela de Prospecção de Clientes", category: "outros" },
  Op85: { label: "Analista Fiscal", category: "financeiro" },
  Op86: { label: "Permite alterar o preço para maior", category: "financeiro" },
  Op87: { label: "Cálculo da Tributação Fiscal", category: "financeiro" },
  Op88: { label: "Destravar Ordem de Serviço", category: "vendas" },
  Op90: { label: "Supervisor Financeiro", category: "financeiro" },
  Op91: { label: "Administrador Geral", category: "config" },
  Op92: { label: "Faturista", category: "financeiro" },
  Op93: { label: "Estoquista", category: "produtos" },
  Op94: { label: "Supervisor de Compras", category: "compras" },
  Op95: { label: "Filtro (Somente as Minhas Vendas)", category: "vendas" },
  Op102: { label: "Subgrupo", category: "produtos" },
  Op103: { label: "Almoxarifado", category: "produtos" },
  Op105: { label: "Estornar Pedido", category: "vendas" },
};

export const PERMISSIONS_LIST: Permission[] = Object.entries(PERMISSIONS_MAP).map(([key, value]) => ({
  key,
  label: value.label,
  category: value.category,
}));

export const CATEGORIES_LABELS: Record<Permission["category"], string> = {
  vendas: "Vendas & OS",
  compras: "Compras",
  financeiro: "Financeiro & Contábil",
  produtos: "Produtos & Estoque",
  contratos: "Contratos",
  locacao: "Locação de Equipamentos",
  config: "Configurações & Acessos",
  outros: "Cadastros Gerais",
};
